--CREATING TABLES
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INTEGER PRIMARY KEY,
    EMP_FIRSTNAME VARCHAR2(50),
    EMP_LASTNAME VARCHAR2(50),
    DEPARTMENT_ID INTEGER,
    SALARY NUMBER(8,2),
    EMP_EMAIL VARCHAR2(50)
);
/
CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID INTEGER PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(100)
);
/
COMMIT;
/
--ADDING FOREIGN KEY CONSTRAINT
ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_DEPARTMENT_ID
    FOREIGN KEY (DEPARTMENT_ID)
    REFERENCES DEPARTMENT (DEPARTMENT_ID);
/
COMMIT;
/
--SETS UP AUTO NUMBERING SEQUENCES
CREATE SEQUENCE EMPLOYEESEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
/
CREATE SEQUENCE DEPARTMENTSEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
/
--ADDS TRIGGER FUNCTIONALITY TO SEQUENCES
CREATE OR REPLACE TRIGGER INCREMENT_ON_INSERT_EMPLOYEE
    BEFORE INSERT ON EMPLOYEE
    FOR EACH ROW
    WHEN (NEW.EMPLOYEE_ID IS NULL)
    BEGIN
    SELECT EMPLOYEESEQ.NEXTVAL
    INTO :NEW.EMPLOYEE_ID
    FROM DUAL;
    END;
/
CREATE OR REPLACE TRIGGER INCREMENT_ON_INSERT_DEPARTMENT
    BEFORE INSERT ON DEPARTMENT
    FOR EACH ROW
    WHEN (NEW.DEPARTMENT_ID IS NULL)
    BEGIN
    SELECT DEPARTMENTSEQ.NEXTVAL
    INTO :NEW.DEPARTMENT_ID
    FROM DUAL;
    END;
/
--INSERTS ROWS INTO DEPARTMENT TABLE
INSERT INTO DEPARTMENT (DEPARTMENT_NAME) VALUES('ENGLISH');
INSERT INTO DEPARTMENT (DEPARTMENT_NAME) VALUES('MATH');
INSERT INTO DEPARTMENT (DEPARTMENT_NAME) VALUES('SCIENCE');
/
--INSERTS ROWS INTO EMPLOYEE TABLE
INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL) VALUES('RICHARD', 'DICOSMO', 4, 120000, 'RJDICOSMO@GMAIL.COM');
INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL) VALUES('JOHN', 'DOE', 5, 100000, 'JD@GMAIL.COM');
INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL) VALUES('JANE', 'DEAR', 6, 130000, 'MJD@GMAIL.COM');
INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL) VALUES('BOB', 'BOBSON', 4, 90000, 'BOBTHEMAN@GMAIL.COM');
INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL) VALUES('BILL', 'BOARD', 5, 120000, 'BB@GMAIL.COM');
INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL) VALUES('RON', 'GUY', 6, 120000, 'RGUY@GMAIL.COM');
/
COMMIT;
/
--SELECT STATEMENT FOR GETTING THE AVERAGE SALARIES IN EACH DEPARTMENT
SELECT DEPARTMENT.DEPARTMENT_NAME, AVG(EMPLOYEE.SALARY) FROM DEPARTMENT INNER JOIN EMPLOYEE ON EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID GROUP BY DEPARTMENT.DEPARTMENT_NAME;